weather:
  api:
    base-url: "https://api.weatherbit.io/v2.0/forecast/daily"
    api-key: "ff98655ba53b4894afd58364b901b4b8"
spring:
  cache:
    type: caffeine
    cache-names: forecasts,bestLocation
    caffeine:
      spec: maximumSize=500,expireAfterAccess=300s

cloud:
  openfeign:
    client:
      config:
        weatherClient:
          default-request-headers:
            api-key: "ff98655ba53b4894afd58364b901b4b8"
